---
collections:
  - name: middleware_automation.jcliff
    version: ">=0.0.15"
  - name: middleware_automation.redhat_csp_download
    version: ">=1.2.1"
  - name: community.general
  - name: community.postgresql
