---
- assert:
    that:
      - rhn_cp_id is defined
      - rhn_username is defined
      - rhn_password is defined
    quiet: true

- name: "Apply patch with ID {{ rhn_cp_id }} to server."
  include_role:
    name: jboss_eap
    tasks_from: apply_cp.yml
  vars:
    rhn_software_id: '101511'

- meta: flush_handlers
