---
- import_playbook: ../../playbooks/preconds.yml
  vars:
    ansible_distribution: 'RedHat'

# PGSL Playbook
- import_playbook: ../../playbooks/postgresql.yml

# JBoss Core Services (Apache HTTPD)
#- import_playbook: jbcs.yml

# Datagrid Playbook
- import_playbook: ../../playbooks/jdg.yml
  vars:
    ansible_distribution: 'RedHat'

# Keycloak Playbook
- import_playbook: ../../playbooks/keycloak.yml
  vars:
    ansible_distribution: 'RedHat'

# Wildfly Playbook
- import_playbook: ../../playbooks/wildfly.yml
  vars:
    ansible_distribution: 'RedHat'

