---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: centos:8
    privileged: true
    command: "/usr/sbin/init"
    etc_hosts:
      jbcs-0: "127.0.0.1"
      wfly-1: "127.0.0.1"
      pgsql-0: "127.0.0.1"
      jdg-1: "127.0.0.1"
      keycloak-0: "127.0.0.1"
    groups:
      - wildfly
      - keycloak
      - jdg
      - pgsql
    port_bindings:
      - "8080/tcp"
      - "8443/tcp"
      - "8009/tcp"
      - "11222/tcp"
      - "5432/tcp"
      - "8280/tcp"
      - "8643/tcp"
      - "8209/tcp"
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
  env:
    CATALINA_HOME: "/opt/apache-tomcat-9.0.50"
    ANSIBLE_FORCE_COLOR: "true"
  inventory:
    links:
      hosts: ../../inventory/hosts
      group_vars: ../../inventory/group_vars
    localhost:
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
      #- idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
