---
dependency:
  name: galaxy
driver:
  name: podman
# lint: |
#   set -e
#   yamllint .
#   flake8
#   ansible-lint --force-color
platforms:
  - name: instance
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    port_bindings:
      - 8080:8080
    published_ports:
      - 0.0.0.0:8080:8080/TCP
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
    ssh_connection:
      pipelining: false
  playbooks:
    converge: ../../playbooks/demo.yml
  env:
    CATALINA_HOME: "/opt/apache-tomcat-9.0.50"
    ANSIBLE_FORCE_COLOR: "true"
  inventory:
    links:
      hosts: ../../inventory/localhost
      group_vars: ../../inventory/group_vars
    localhost:
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # -   idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
