---
- name: Prepare
  hosts: all
  tasks:
    - name: Install required packages
      yum:
        use_backend: dnf
        name: 
          - sudo
          - iproute
          - net-tools
        state: present
