---
- name: Prepare
  hosts: all
  tasks:
    - name: Install required packages
      yum:
        use_backend: dnf
        name: 
          - sudo
          - iproute
          - net-tools
          - bind-utils
          - glibc-locale-source
          - glibc-langpack-en
        state: present
    - name: Upgrade systemd (for postgres)
      yum:
        use_backend: dnf
        name:
          - systemd
        state: latest
