---
- assert:
    that:
      - rhn_eap_download_url is defined
      - workdir is defined
      - rhn_username is defined
      - rhn_password is defined
    quiet: true

- set_fact:
    target_dir: "{{ wildfly.home }}"
  when:
    - not target_dir is defined
    - wildfly is defined
    - wildfly.home is defined

- assert:
    that:
      - target_dir is defined
    quiet: true

- include_tasks: tasks/download_from_rhn.yml
  vars:
    download_url: "{{ rhn_eap_download_url  }}"
    zipfile: "{{ eap_zipfile }}"

- name: "Decompress {{ eap_zipfile }} into {{ workdir }} (results in {{ target_dir }}."
  unarchive:
    src: "{{ eap_zipfile }}"
    dest: "{{ workdir }}"
    owner: "{{ wildfly.user }}"
    group: "{{ wildfly.user }}"
    remote_src: yes
    creates: "{{ target_dir }}"
  when:
    - path_to_downloaded_artefact is defined
    - path_to_downloaded_artefact.stat is defined
    - path_to_downloaded_artefact.stat.exists
