---
- set_fact:
    demo_app_redirect_uris: []
    origin_host: localhost

- name: Use loadbalancer as origin when defined
  set_fact:
    origin_host: "{{ groups['jbcs'][0] }}"
  when: groups['jbcs'] is defined and groups['jbcs'][0]|length > 0

- name: Interpolate web origins list
  set_fact:
    demo_app_redirect_uris: "{{ demo_app_redirect_uris + item }}"
  loop:
    - [ "https://{{ origin_host }}{{ demo_app_endpoint }}/*"]

- set_fact:
    app_servers_list: []

- include_tasks: demo_app_urls.yml
  with_items:
    - "{{ groups['wildfly'] }}"

- set_fact:
    demo_app_redirect_uris: "{{ demo_app_redirect_uris }} + ['{{ item }}{{ demo_app_endpoint }}/*']"
  with_items:
    - "{{ app_servers_list }}"

- debug:
    msg: "demo_app_redirect_uris: {{ demo_app_redirect_uris }}"
  when:
    - debug_redirects_urls is defined
