---
- name: Playbook for EAP hosts
  hosts: eap
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.jcliff
  roles:
    - redhat_csp_download
    - jcliff
  vars:
    wildfly_home: '/opt/jboss-eap-7.3'
  tasks:

    - name: "Update EAP to latest"
      include_role:
        name: 3trains_eap
        tasks_from: update.yml
      vars:
        rhn_cp_id: "{{ upgrade_eap_software_id | default('101511') }}"

    - meta: flush_handlers

    - wait_for:
        port: 9990

    - include_role:
        name: 3trains_eap
        tasks_from: jboss_cli.yml
      vars:
        wildfly_home: "{{ wildfly.home }}"
        jboss_cli_query: "/core-service=patching:patch-info"

    - debug:
        msg: "{{ jboss_cli_results.stdout }}"

    - include_role:
        name: 3trains_eap
        tasks_from: check.yml
      loop:
        - java.runtime.version
        - 'WFLYSRV0025: JBoss EAP'
