---
- name: Playbook for JBCS Hosts
  hosts: jbcs
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - redhat_csp_download
  tasks:
    - set_fact:
        override_jbcs_bind_address: "{{ ansible_nodename }}"
    - name: "JBoss Core Services"
      include_role:
        name: 3trains_jbcs
