---
- name: Playbook for JDG Hosts
  hosts: jdg
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.infinispan
  roles:
    - redhat_csp_download
  tasks:
    - name: "Configure firewalld for Red Hat Data Grid"
      include_role:
        name: infinispan
        tasks_from: firewalld.yml
    - name: "Install Red Hat Data Grid"
      include_role:
        name: infinispan
      vars:
        infinispan_users: "{{ user_accounts }}"
        supervisor_password: "{{ admin_pass }}"
    - name: "Create kitchensink cache"
      include_role:
        name: infinispan_cache
      vars:
        deployer_password: "{{ admin_pass }}"
        cache_xml: >
             <local-cache name="kitchensink_sql_cache" statistics="true">
               <encoding media-type="application/x-protostream"/>
             </local-cache>