---
- name: Playbook to validate host met the preconditions
  hosts: all
  tasks:

    - assert:
        that:
          - ansible_distribution is defined
          - ansible_distribution == "RedHat"
          - ansible_distribution_version is defined
          - ansible_distribution_version is version('8.4','>=')
          - ansible_version is defined
          - ansible_version.string is version('2.9','>')
          - ansible_python_version is defined
          - ansible_python_version is version('3.6','>')
        quiet: true
        fail_msg: "This demo has been built for RHEL 8.4+ (found {{ansible_distribution}} {{ansible_distribution_version}}) using Ansible 2.9 ({{ansible_version.string}}) running on Python 3 ({{ansible_python_version}})"
      when: ansible_facts['virtualization_type'] not in ['docker','oci','containerd','podman']

    - name: "Ensure target system {{ ansible_nodename }} is properly registered"
      become: yes
      community.general.redhat_subscription:
        state: present
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        auto_attach: true
      when:
        - rhn_username is defined
        - rhn_password is defined
        - ansible_facts['virtualization_type'] not in ['docker','oci','containerd','podman']

    - name: "Ensure that OS has the required packages installed"
      include_role:
        name: 3trains_fastpackages
      vars:
        packages_list:
          - yum-utils
          - hostname
          - net-tools
          - iproute
          - bind-utils
          - glibc-locale-source
          - glibc-langpack-en
