---
- name: Playbook for Wildfly Hosts
  hosts: wildfly
  collections:
    - middleware_automation.jcliff
    - middleware_automation.redhat_csp_download
  roles:
    - redhat_csp_download

  tasks:
    - name: JCliff
      include_role:
        name: jcliff

    - name: Wildfly/EAP Role
      include_role:
        name: 3trains_wildfly
      vars:
        keycloak_3trains_url: "{{ 'http://' + (groups['keycloak'][0] if groups['keycloak']| length > 0 else 'localhost')  + ':8080' }}"
