---
- name: Playbook for Wildfly Hosts
  hosts: wildfly
  vars:
    wildfly_home: /opt/wildfly/wildfly-26.0.1.Final
  collections:
    - middleware_automation.jcliff
    - middleware_automation.wildfly
    - middleware_automation.redhat_csp_download
  roles:
    - redhat_csp_download

  tasks:
    - name: JCliff
      include_role:
        name: jcliff

    - name: Wildfly/EAP Role
      include_role:
        name: flange_wildfly
